### PR TITLE
Updated support Python and Django versions

### PR DESCRIPTION
**Pull request by smithdc1**
## Description
Added support for Python 3.9 and Django 3.1. Support for Python 3.5 has been removed in line with other Jazzband projects. 

## How Has This Been Tested?
Run tox locally, all tests pass. Also tested with warnings to identify and deprecation warnings. Two items highlighted were removal or `url()` and the `django-admin.py` entry point. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jezdez** [comment]
There is a chance that some of this overlaps with #126 😬

**Comment by smithdc1** [comment]
It is ok. I can re-work this once your pr is merged.

**Review by mbeijen — APPROVED** [review]

**Comment by smithdc1** [comment]
😬 not sure we we were going to merge this quite so quickly.

**Comment by mbeijen** [comment]
@smithdc1 I'm sorry, I misread, I thought you wanted _this_ merged before the github actions PR 😢 

Should I revert this one in master?

**Comment by smithdc1** [comment]
Sorry for any confusion. 

I'm not sure what @jezdez would prefer from here. 

I'm busy for the next few hours but I'm happy to try and raise a pr to his branch to fix the merge conflicts? (I've not looked, but I'm expecting there will be a fair amount).

**Comment by jezdez** [comment]
> Sorry for any confusion.
> 
> I'm not sure what @jezdez would prefer from here.
> 
> I'm busy for the next few hours but I'm happy to try and raise a pr to his branch to fix the merge conflicts? (I've not looked, but I'm expecting there will be a fair amount).

No problem, I'll rebase my PR with the current master. Thanks all!

**Pull request merged**
